### ISSUE TITLE
Страница MT4 Platform

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#119]
http://new.icmcapital.co.uk/mt4/platform/
1. Не отображаются картинки на кнопках
2. Поправить отступы по краям серых блоков
3. на планшетном разрешении кнопки внутри блоков не пероносить на другую строку, переносить только для мобильного

**Comment by gudimdv** [comment]
на планшетном разрешении кнопки внутри блоков не пероносить на другую строку, переносить только для мобильного

**Comment by satanworker** [comment]
Сделал чуть по другому, очень уж убого смотрелось
