### ISSUE TITLE
Блок Exceptional ECN Trading отображать на планшетном разрешении

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#128]
![image](https://cloud.githubusercontent.com/assets/3957855/11418769/23e5a33a-9434-11e5-9678-e9d9b7c24eca.png)
![image](https://cloud.githubusercontent.com/assets/3957855/11418817/68370cf4-9434-11e5-877e-667ba1087bc2.png)

**Comment by satanworker** [comment]
done
