### ISSUE TITLE
На планшетном разрешении формы отображать в десктоп режиме (2 колонки)

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#139]
Сейчас:
![image](https://cloud.githubusercontent.com/assets/3957855/11531964/ae7b39ba-9911-11e5-8fd2-f5bdec0d1f84.png)

Должно быть:
![image](https://cloud.githubusercontent.com/assets/3957855/11531984/cb9579ac-9911-11e5-84a6-1021c770c5b8.png)

**Comment by satanworker** [comment]
done
