### ISSUE TITLE
Проработать страничку trading products

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#141]
http://new.icmcapital.co.uk/accounts/products/
https://invis.io/4P562VHQU

**Comment by satanworker** [comment]
Стилизовал текст, верстка уже была))

**Comment by gudimdv** [comment]
Наложить затемняющую маску на изображения
Поставить корректные шрифты
Вынести стили из разметки в less
\WebApp\Views\Partials\Grid\Editors\PageLinkListSkins\LinksWithImages.cshtml

**Comment by satanworker** [comment]
done
