### ISSUE TITLE
Доработка элементов управления выполненных на основе select2

### ISSUE THREAD

**Issue by SergeyLimonov** [satanworker/finance#143]
1) Если, после появления выпадающего списка в любом select2 элементе управления, не делать выбор из этого списка, а, например, установить фокус на другом элементе управления, то выпадающий список не сворачивается. Необходимо его сворачивать, если этот элемент управления теряет фокус.

2) Выпадающий список с кодами телефонов, криво отображает флажки (см. прикрепленное изображение).

3) На главной странице, выпадающий список с кодами телефонов, отображается с неверным z-index (см. прикрепленное изображение).

![image](https://cloud.githubusercontent.com/assets/12935645/11563752/9ea098de-99e6-11e5-9b9d-390db243c673.png)

**Comment by satanworker** [comment]
не смогу только увидеть проблему со сменой фокуса
