### ISSUE TITLE
В попап окнах неверно отображаются выпадающие списки

### ISSUE THREAD

**Issue by SergeyLimonov** [satanworker/finance#146]
1)
![image](https://cloud.githubusercontent.com/assets/12935645/11568578/0f7dc0ba-99fe-11e5-951a-a980cf3083f8.png)
![image](https://cloud.githubusercontent.com/assets/12935645/11568604/2ec42f2c-99fe-11e5-9f91-6a74b9eaf06a.png)
вероятно вследствие неверного z-index

2) select2 некорректно отображается в попап окнах

**Comment by satanworker** [comment]
done
