### ISSUE TITLE
Стилизовать таблицы на сайте!!!

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#151]
Все таблицы с классом content-table должны быть стилизованы в соответствии с макетом

**Comment by gudimdv** [comment]
http://new.icmcapital.co.uk/accounts/products/spot-foreign/
http://new.icmcapital.co.uk/accounts/products/otc-precious-metals/
http://new.icmcapital.co.uk/accounts/products/otc-us-stocks/

**Comment by gudimdv** [comment]
добавить полосатость

**Comment by satanworker** [comment]
добавил, нужно проверить только rowspan

**Comment by satanworker** [comment]
и нужны ховеры
