### ISSUE TITLE
Расстояние между параграфами в аккордионе отсутвует

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#153]
http://new.icmcapital.co.uk/accounts/trading-tools/
![image](https://cloud.githubusercontent.com/assets/3957855/11657001/184f9716-9dca-11e5-94f2-9153e87a876f.png)

**Comment by gudimdv** [comment]
если контент обернут в div он не отображается
все элементы должны иметь поведение как и в basic-page, отступы от заголовков, картинок, параграфов, ссылок, кнопок и т.д.

**Comment by satanworker** [comment]
done
