### ISSUE TITLE
Popup формы отображаются некорректно

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#158]
Формы должны отображаться по центру

http://new.icmcapital.co.uk/mt4/iphone/
http://new.icmcapital.co.uk/mt4/mac/
http://new.icmcapital.co.uk/mt4/desktop/
http://new.icmcapital.co.uk/mt4/android/

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/11777624/9bfee11c-a260-11e5-899b-8e4a197a4948.png)

**Comment by satanworker** [comment]
done
