### ISSUE TITLE
Добавить корректное правило CSS для отображения ошибки в элементе управления IntlTelInput

### ISSUE THREAD

**Issue by SergeyLimonov** [satanworker/finance#162]
Для следующего контрола селектор в CSS для отображения ошибки задан корректно
![image](https://cloud.githubusercontent.com/assets/12935645/11723992/585e10b2-9f82-11e5-8b2e-47df53f489bf.png)

А для следующего всплывающее окошко с ошибкой не отображается
![image](https://cloud.githubusercontent.com/assets/12935645/11724024/7bd39094-9f82-11e5-8f57-059085399ffd.png)

Полагаю это связано с тем что селектор не учитывает что во втором случае что тег input и span не располагаются в одном элементе контейнере, друг за другом, как в первом варианте.

**Comment by SergeyLimonov** [comment]
аналогичная проблема с select2 на форме на страницах

**Comment by satanworker** [comment]
done
