### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#166]
Расположение блоков должно отталкиваться от body dir="rtl"

Для арабского необходимо использовать font-family: "Droid Arabic Naskh",Arial,sans-serif;

Link

@import url(http://fonts.googleapis.com/earlyaccess/droidarabicnaskh.css);
Example

font-family: 'Droid Arabic Naskh', serif;

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/11867839/cdad60ba-a4c4-11e5-8639-56ac3d687042.png)

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/11867882/0b55bbc4-a4c5-11e5-9dbe-39eb26eab62d.png)

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/11867911/58546434-a4c5-11e5-922b-8fdd67eb530d.png)

**Comment by satanworker** [comment]
done
