### ISSUE TITLE
RTL. Bottom menu. длинные элементы меню переносить на новую строку

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#176]
В языках с длинными текстами нужно делать перенос на другую строку, чтобы убирались все элементы верхнего уровня в одну строчку
![image](https://cloud.githubusercontent.com/assets/3957855/11912447/cf07a602-a64d-11e5-8234-c918cd1a34a3.png)

**Comment by satanworker** [comment]
сделал только для большого разрешения
