### ISSUE TITLE
tab control. Растянуть подчеркивание на весь экран

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#178]
![image](https://cloud.githubusercontent.com/assets/3957855/11917982/e577322c-a72e-11e5-8cf5-eddc9c5026ef.png)
![image](https://cloud.githubusercontent.com/assets/3957855/11917989/2df42d34-a72f-11e5-9501-6ccaa3bd1492.png)

http://new.icmcapital.co.uk/news/championship/live/
http://new.icmcapital.co.uk/education/trading-examples/forex/

**Comment by satanworker** [comment]
done
