### ISSUE TITLE
Economic CalendarУбрать горизонтальную полосу 

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#184]
Унаследовалось от tab-control повидимому
![image](https://cloud.githubusercontent.com/assets/3957855/12019830/401a635e-ad86-11e5-9c40-9a148088e39d.png)

**Comment by gudimdv** [comment]
http://new.icmcapital.co.uk/accounts/trading-tools/

**Comment by satanworker** [comment]
done
