### ISSUE TITLE
минимальный размер кнопок  внутри контента flat orange

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#185]
Необходимо ограничить минимальный размер и выровнять текст только для ссылок внутри контента 
min-width: 200px;
    text-align: center;

http://new.icmcapital.co.uk/cn/accounts/trading-central/

![image](https://cloud.githubusercontent.com/assets/3957855/12020330/48dce9a2-ad8c-11e5-89d5-91393b50621c.png)

**Comment by satanworker** [comment]
done
