### ISSUE TITLE
Не переносить кнопку submit в планшетном разрешении на отдельную строку

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#187]
Десктоп:
![image](https://cloud.githubusercontent.com/assets/3957855/12232821/f5a5415c-b872-11e5-923c-14a4eb909b59.png)

Планшет:
![image](https://cloud.githubusercontent.com/assets/3957855/12232831/02544538-b873-11e5-94b3-8cf70689808b.png)

**Comment by satanworker** [comment]
done
