### ISSUE TITLE
Леэблы на формах не восстанавливают свое состояние после обновления

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#194]
После ajax отправки формы лейблы меняют свое расположение:

До обновления:
![image](https://cloud.githubusercontent.com/assets/3957855/12327442/a0d79798-bae7-11e5-8fbe-0959c6ba3c6e.png)

После обновления:

![image](https://cloud.githubusercontent.com/assets/3957855/12327450/aa4b27e0-bae7-11e5-87b0-3c47f4524649.png)

**Comment by satanworker** [comment]
в ajax callback нужно вызвать вот эту функцию 
labelResize();
