### ISSUE TITLE
Исправить баги в верстке

### ISSUE THREAD

**Issue by SergeyLimonov** [satanworker/finance#201]
1) ![image](https://cloud.githubusercontent.com/assets/12935645/12617765/2c7350fa-c522-11e5-9d05-78e6326abf72.png)
2) если открыть форму всплывающую, то скрывается скроллер страницы, если затем закрыть форму нахав на крестик в правом верхнем углу, то форма закрывается и скроллер страницы снова появляется, но если закрывать форму не нажимая крестик, а используя клавишу Esc, то форма закрывается , но скроллер страницы не появляется.
3) после сабмита формы, если неверно указать проверочный код, то сообщение об ошибке закрывает собой это поле, при получении фокуса ввода полем.
![image](https://cloud.githubusercontent.com/assets/12935645/12676213/748f091c-c6a1-11e5-9302-39cc10267b0e.png)

**Comment by satanworker** [comment]
done
