### ISSUE TITLE
Сообщение об удачном/неудачном завершении формы не центрируется по вертикали

### ISSUE THREAD

**Issue by SergeyLimonov** [satanworker/finance#204]
Если форма по высоте очень маленькая, то сообщение о завершении работы формы отображается некорректно. Например, на странице http://new.icmcapital.co.uk/mt4/desktop/ форма загрузки:

![image](https://cloud.githubusercontent.com/assets/12935645/12781878/37b1c4f4-ca88-11e5-8fca-184e909d5794.png)

**Comment by satanworker** [comment]
вьюхен - ~/Views/MacroPartials/Forms/Form2015.cshtml

**Comment by satanworker** [comment]
DONE
