### ISSUE TITLE
New Main. Несоответвия макету

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#210]
![image](https://cloud.githubusercontent.com/assets/3957855/13003269/c44b1650-d185-11e5-8972-f0fd8affe58d.png)

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/13003322/0f293198-d186-11e5-9222-717175eb769a.png)

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/13003438/a58fcafc-d186-11e5-8695-c1c731b864e7.png)

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/13003467/c5d4cc36-d186-11e5-9bd9-e156750728e0.png)

**Comment by satanworker** [comment]
done
