### ISSUE TITLE
New Main mobile. Несоответствие макету

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#211]
![image](https://cloud.githubusercontent.com/assets/3957855/13002993/e2d0430e-d183-11e5-984b-f937ee592329.png)

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/13003048/2e3840da-d184-11e5-9696-7014a23c4414.png)

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/13003083/7cb94448-d184-11e5-9c75-ff5a25f3d67f.png)

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/13003149/ddf7ffec-d184-11e5-802c-cc8f5c34cd6c.png)

**Comment by gudimdv** [comment]
![image](https://cloud.githubusercontent.com/assets/3957855/13003198/26e8ea40-d185-11e5-8e01-2acb2c99a83a.png)

**Comment by satanworker** [comment]
done
