### ISSUE TITLE
Economic Calendar. главная

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#212]
Привести заголовок к макетному виду
![image](https://cloud.githubusercontent.com/assets/3957855/13045091/8cf134d2-d3e2-11e5-97d9-ea38e16756ee.png)

**Comment by gudimdv** [comment]
Отсортировать по времени
![image](https://cloud.githubusercontent.com/assets/3957855/13045103/a146404e-d3e2-11e5-9951-4d4c8e9630b2.png)

**Comment by gudimdv** [comment]
Завести для флагов отедльную колонку в таблице. Чтобы текст был выравнен одинаков
![image](https://cloud.githubusercontent.com/assets/3957855/13045139/c47572a6-d3e2-11e5-8445-2ccd13edeb5e.png)

**Comment by gudimdv** [comment]
Выравнять заголовки колонок по центру (см макет)
![image](https://cloud.githubusercontent.com/assets/3957855/13045188/0b1d9300-d3e3-11e5-822f-8346e53c7666.png)

**Comment by gudimdv** [comment]
Колонки с цифрами сместить влево и цифры выровнять по правому краю
![image](https://cloud.githubusercontent.com/assets/3957855/13045229/330c0a18-d3e3-11e5-9db1-7754ce0764ae.png)

**Comment by gudimdv** [comment]
Брать данные о периоде и культуре из view 
![image](https://cloud.githubusercontent.com/assets/3957855/13045406/225465d4-d3e4-11e5-9bce-12a950680bdb.png)

**Comment by satanworker** [comment]
Заголовки done

**Comment by satanworker** [comment]
выровнял шапку по центру, если выровнять текста по правому краю, получается уг, в макете по левому

**Comment by satanworker** [comment]
флаги done

**Comment by satanworker** [comment]
сортировка done

**Comment by satanworker** [comment]
некроссбраузерное время done all done, кроме скролла к нынешней дате, его после пула правок
