### ISSUE TITLE
Мобильное меню

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#214]
Мобильное меню второго уровня может содержать ссылки, сейчас нет возможности переходить по ссылкам на этом уровне, вместо это меню разворачивается. Необходимо перенести функционал раскрытия на плюсик справа. Пример нерабочей ссылки можно увидеть на разделе Contacts

**Comment by gudimdv** [comment]
для коммита необходимо проставить ключ WS-569

**Comment by satanworker** [comment]
done
