### ISSUE TITLE
Main page. Косячки

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#215]
Firefox. Некорректно отображаются спрайты
![image](https://cloud.githubusercontent.com/assets/3957855/13079615/21ff3a80-d4d6-11e5-91d3-2f2f0d32e79f.png)

**Comment by gudimdv** [comment]
ссылки отображаются некорректно. должен быть белый цвет и подчеркивание при наведении
![image](https://cloud.githubusercontent.com/assets/3957855/13079639/4eb40f24-d4d6-11e5-8c95-dc7dca108c0a.png)

**Comment by gudimdv** [comment]
Меню в подвале, второй уровень,  выделить жирным
![image](https://cloud.githubusercontent.com/assets/3957855/13079754/cb3e5d10-d4d6-11e5-9a80-4f8ff79e07e0.png)

**Comment by gudimdv** [comment]
Зафиксировать ширину кнопок
![image](https://cloud.githubusercontent.com/assets/3957855/13079795/fc5aca82-d4d6-11e5-8282-be35a050522f.png)

**Comment by gudimdv** [comment]
Выровнять блок новостей по краям
![image](https://cloud.githubusercontent.com/assets/3957855/13079837/251c423e-d4d7-11e5-83b3-cc87839f627a.png)

**Comment by gudimdv** [comment]
После закрытия видео остается полоса с кривым фоном. Убрать старый фон и возвращать меню.
![image](https://cloud.githubusercontent.com/assets/3957855/13079993/dd1a7af4-d4d7-11e5-92ed-c2c35357339f.png)

**Comment by gudimdv** [comment]
Убрать анимацию при ресайзе (переход с десктоп к мобилке) с кнопки Apply for demo. 
![image](https://cloud.githubusercontent.com/assets/3957855/13080537/2fdf4556-d4da-11e5-9e1b-261965cc2d38.png)

**Comment by gudimdv** [comment]
Выровнять заголовки по центру
![image](https://cloud.githubusercontent.com/assets/3957855/13082226/e369c280-d4e0-11e5-9e11-a6d8c9af4e9d.png)

**Comment by satanworker** [comment]
advantages done
links done

**Comment by satanworker** [comment]
economic calendar done

**Comment by satanworker** [comment]
news done

**Comment by satanworker** [comment]
menu on popup close done

**Comment by satanworker** [comment]
apply buttons done
