### ISSUE TITLE
Нужно повесить анимации на кнопки

### ISSUE THREAD

**Issue by HarleyQueen** [satanworker/finance#216]
![83ec3ae6561abc3e50118d88cd70d40b-1](https://cloud.githubusercontent.com/assets/11504769/13144969/c3d736c6-d65e-11e5-8ea3-3781cce1c434.png)

http://ianlunn.github.io/Hover/
на все кнопки вешаем анимацию: Back Pulse
На примере кнопок apply: Левую кнопку с обводкой заливаем: 69DBE8 текст на ней делаем белым
Правую кнопку при ховере 69DBE8

![7436aca0a46cd136239577cdcbc3b0b3](https://cloud.githubusercontent.com/assets/11504769/13146228/c5757220-d665-11e5-9803-3665fec80837.png)
 на примере календаря, кнопки окрашиваем при хвовере в цвет обводки

А на все кнопки read more вешаем этот ховер эффект: http://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_buttons_animate1

**Comment by satanworker** [comment]
done
