### ISSUE TITLE
Косячки 2 очередь.

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#217]
кнопка ICM Access едет при изменении текста
![image](https://cloud.githubusercontent.com/assets/3957855/13146493/1d03b730-d667-11e5-9bd7-a4c8c52ecdfc.png)

**Comment by gudimdv** [comment]
Арабский логотип едет при изменении текста кнопки access
![image](https://cloud.githubusercontent.com/assets/3957855/13146550/66be3b0c-d667-11e5-8888-81bc26c67c68.png)

**Comment by gudimdv** [comment]
Заголовки popup форм смещены относительно заголовка
![image](https://cloud.githubusercontent.com/assets/3957855/13146644/cd7d171e-d667-11e5-8dcd-ce1bb27fcb5a.png)

**Comment by gudimdv** [comment]
Мобильный каллендарь в RTL отображается криво. + стилизовать мобильный скролл 
![image](https://cloud.githubusercontent.com/assets/3957855/13146751/39641a54-d668-11e5-9e0c-33a76c2cdb56.png)

**Comment by satanworker** [comment]
header rtl done

**Comment by satanworker** [comment]
rtl mobile calendar done

**Comment by satanworker** [comment]
popup done
