### ISSUE TITLE
Найди 10 отличий

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#22]
http://clip2net.com/s/3nFaggr

**Comment by gudimdv** [comment]
http://c2n.me/3nFWM8A кнопки должны быть залиты не только на мобильной версии

**Comment by satanworker** [comment]
В новом макете кажется нет 
<img width="597" alt="2015-09-19 17 56 22" src="https://cloud.githubusercontent.com/assets/11026240/9976791/c950f27e-5ef7-11e5-94fd-7e84f2cdac08.png">
