### ISSUE TITLE
Анимации 

### ISSUE THREAD

**Issue by HarleyQueen** [satanworker/finance#24]
1) На все кнопки на сайте вешаем вот этот эффект: http://tympanus.net/Development/CreativeButtons/
тот что первый в списке.
2) https://gyazo.com/aef0a65066af9b0f2abb289350d1e181
На эту вешаем "grow" отсюда: http://ianlunn.github.io/Hover/
3) https://gyazo.com/ab0f567bd5b4603b972bba8a79485ab8 Сюда на дроп нужно добавить плавность 
4) https://gyazo.com/3fe934cd5237948fc7f946322add2c78 здесь тоже нужно сделать плавное проявление
5) на кнопку гамбургера нужно сделать вот такой эффект: https://d13yacurqjgara.cloudfront.net/users/108183/screenshots/2207652/menu-and-close.gif

**Comment by HarleyQueen** [comment]
6) https://gyazo.com/cdf3330a6b417a2c6b964e80faee09b3 при скролле нужно сделать небольшой паралакс этого телефона, что бы он слегка выезжал наверх

**Comment by HarleyQueen** [comment]
7) https://gyazo.com/8a32cc9beeb7d4d74394f3653c4fca3a здесь тоже нужно сделать плавность проявления

**Comment by satanworker** [comment]
что не получилось, плавное появление тут
https://gyazo.com/ab0f567bd5b4603b972bba8a79485ab8 
гамбургер
