### ISSUE TITLE
Тень, цвет и разное кол-во полей

### ISSUE THREAD

**Issue by Scald2** [satanworker/finance#38]
Не знаю на сколько это важно, но Тень в оригинале не так видна.
Цвет рамки полей не серый, а синий
Также разное кол-во полей
Выравнивание ни как в оригинале, хотя мне нравиться больше:-)
![shade and color](https://cloud.githubusercontent.com/assets/14565864/9994832/c7d405d0-6087-11e5-8258-b192f0ac4994.jpg)

**Comment by gudimdv** [comment]
Количество полей корректно, цвет должен быть по умолчанию серый, голубой при фокусе

**Comment by satanworker** [comment]
там были примеры успешно заполненного поля

**Comment by Scald2** [comment]
По дизайну, он голубой с неким свечением, посмотри как Артур сделал

С уважением,
Дмитрий
