### ISSUE TITLE
Не должно быть подчеркивания 

### ISSUE THREAD

**Issue by Scald2** [satanworker/finance#39]
При наведении не должно быть подчеркивания
![excess underscore](https://cloud.githubusercontent.com/assets/14565864/9995157/4442b124-6089-11e5-839e-d907b34b3b93.jpg)

**Comment by gudimdv** [comment]
При наведении должно быть подчеркивание

**Comment by Scald2** [comment]
В дизайне сказано обратное. Это не ссылки

С уважением,
Дмитрий

**Comment by satanworker** [comment]
я ничего не понял, отпишитесь убрать подчёркивание или нет

**Comment by Scald2** [comment]
Как Денис скажет так и будет. 

 

Best regards.

Dmitri Burmatov

+7 926 382 93 18

**Comment by gudimdv** [comment]
Все ОК
