### ISSUE TITLE
Отсутвуют отсупы меню второго уровня (верхнее/нижнее) (RTL/LTR)

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#44]
![image](https://cloud.githubusercontent.com/assets/3957855/10014425/c10fefb2-6121-11e5-8422-f58eb42a7b91.png)
![image](https://cloud.githubusercontent.com/assets/3957855/10014457/065fa508-6122-11e5-9973-41763b11767b.png)

**Comment by satanworker** [comment]
done

**Comment by gudimdv** [comment]
Нижнее меню не поправил

**Comment by satanworker** [comment]
сделал
