### ISSUE TITLE
Нижнее меню, планшетное разрешение выравнять колонки, сделать отступы

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#48]
![image](https://cloud.githubusercontent.com/assets/3957855/10014801/801ce3ea-6124-11e5-835c-5767c025bf71.png)
![image](https://cloud.githubusercontent.com/assets/3957855/10014816/a35e22ec-6124-11e5-9a44-23deb5f0145e.png)

**Comment by satanworker** [comment]
done
