### ISSUE TITLE
Поменять видое и картинку в слайдере

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#58]
Видео http://www.youtube.com/watch?v=Thq-ufAtQZg
Картинку Аниме убрать и вставить http://previews.123rf.com/images/yellowj/yellowj0906/yellowj090603931/5019487-financial-seminar-professional-business-background-Stock-Photo.jpg

Уменьшить картинку с девкой до 2000px и поставить качество jpg до 60%

**Comment by satanworker** [comment]
done
