### ISSUE TITLE
Убрать поле Verefication Code вместно него разместить кнопку Submit

### ISSUE THREAD

**Issue by gudimdv** [satanworker/finance#80]
![image](https://cloud.githubusercontent.com/assets/3957855/10307659/54fca040-6c39-11e5-90aa-a93d4dd338a9.png)

**Comment by Scald2** [comment]
Поле captcha должно иметь левую границу?
captcha - как это слово вообще переводиться, может лучше Verefication Code как это обычно сделано

**Comment by satanworker** [comment]
поставил кнопку, закоментировал инпут, если что можем поменять
