### ISSUE TITLE
Подсвечивается не то меню второго уровня

### ISSUE THREAD

**Issue by Scald2** [satanworker/finance#86]
![default](https://cloud.githubusercontent.com/assets/14565864/10308518/e091ff6a-6c3e-11e5-924a-1a86b241fe0c.jpg)
http://satanworker.github.io/finance/main/form_RTL.html#
http://satanworker.github.io/finance/main/form_LTL.html#
http://satanworker.github.io/finance/main/awards_RTL.html#
http://satanworker.github.io/finance/main/aboutus_RTL.html

**Comment by gudimdv** [comment]
Это неважно, наполнение не тестируем
