### ISSUE TITLE
Название поля остается вне поля, если оставить его пустым

### ISSUE THREAD

**Issue by Scald2** [satanworker/finance#91]
Название поля остается вне поля, если оставить его пустым, даже если уйти с этого поля

Возможно фича

![image](https://cloud.githubusercontent.com/assets/14565864/10576671/b0a9b368-766d-11e5-8197-a4a06f734150.png)

**Comment by satanworker** [comment]
тоже не знаю, подсказка на место вообще не возвращается на данный момент
